- name: Provision a VM on VMware vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Deploy VM from template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        cluster: "{{ cluster_name }}"
        folder: "{{ vm_folder }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
        networks:
          - name: "{{ network_name }}"
            ip: "{{ vm_ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
        disk:
          - size_gb: "{{ disk_size }}"
            type: thin
            datastore: "{{ datastore_name }}"
      delegate_to: localhost
